name: Graylist
main: de.bootko.graylist.Graylist
version: 1.2.1
author: Zethrus

commands:
    graylist:
      description: Root command to manage
      aliases: [glist, graylist]
      permission: graylist.admin
    sendwelcome:
      description: Command to send out welcome email
      permission: graylist.email

permissions:
    graylist.*:
        description: Grants full abilities to manage the graylist
        default: op
        children:
            graylist.bypass: true
            graylist.admin: true
            graylist.email: true
