name: Graylist
main: de.bootko.graylist.Main
version: 1.2.1
author: Zethrus

commands:
    graylist:
      description: Command for managing Graylist.
      aliases: [glist, greylist]
      permission: graylist.admin
    sendwelcome:
      description: Command to send out welcome email.
      permission: graylist.email

permissions:
    graylist.*:
        description: Grants full administrative capabilities.
        default: op
        children:
            graylist.bypass: true
            graylist.admin: true
            greylist.email: true
